### ISSUE TITLE
Out of date information

### ISSUE THREAD

**Issue by KoboldShenanigans** [Nia292/tw-map#3]
The map mod was nice for a time. But your over a year out of date.
You have incorrect locations for some, and missing locations / data info for the others.
People keep being directed to your TW mod map, and keep getting lost because half the thralls aren't even in it.

**Comment by Nia292** [comment]
@KoboldShenanigans 

This is a free resource and everyone can, and is supposed to, contribute. 

If you are unhappy with the data, fix it. I'm not playing the game at the moment. There are 3 ways to contribute mentioned on the map itself.
